sudo: false

services:
  - mongodb

rvm:
  - 2.3.1

before_install:
  - gem install bundler

env:
  - MONGOID_VERSION=3
  - MONGOID_VERSION=4
  - MONGOID_VERSION=5
  - MONGOID_VERSION=6

language: ruby

cache: bundler
