sudo: false

services:
  - mongodb

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - 2.2.4
  - 2.3.0

before_install:
  - gem install bundler

env:
  - MONGOID_VERSION=3
  - MONGOID_VERSION=4
  - MONGOID_VERSION=5
  - MONGOID_VERSION=6

language: ruby

cache: bundler
